// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sgtoncyrwpvhhatilzrf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNndG9uY3lyd3B2aGhhdGlsenJmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4NTM0NTgsImV4cCI6MjA3MDQyOTQ1OH0.cedwSFkB2g83I6d9zgh5WxzGjU7sZdMyevaLzN1z6Us";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});